export const types = [
  {
    name: "Bug",
    weaknesses: ["Fire", "Flying", "Poison", "Rock"],
    strengths: ["Grass", "Psychic"],
    resistances: ["Grass", "Fighting", "Ground"],
    immunes: [],
  },
  {
    name: "Dragon",
    weaknesses: ["Ice", "Dragon"],
    strengths: ["Dragon"],
    resistances: ["Fire", "Water", "Electric", "Grass"],
    immunes: [],
  },
  {
    name: "Electric",
    weaknesses: ["Ground"],
    strengths: ["Flying", "Water"],
    resistances: ["Electric", "Flying"],
    immunes: [],
  },
  {
    name: "Fighting",
    weaknesses: ["Flying", "Psychic"],
    strengths: ["Ice", "Normal", "Rock"],
    resistances: ["Bug", "Rock"],
    immunes: [],
  },
  {
    name: "Fire",
    weaknesses: ["Ground", "Rock", "Water"],
    strengths: ["Bug", "Grass", "Ice"],
    resistances: ["Fire", "Grass", "Bug"],
    immunes: [],
  },
  {
    name: "Flying",
    weaknesses: ["Electric", "Ice", "Rock"],
    strengths: ["Bug", "Fighting", "Grass"],
    resistances: ["Grass", "Fighting", "Bug"],
    immunes: ["Ground"],
  },
  {
    name: "Ghost",
    weaknesses: ["Ghost"],
    strengths: ["Ghost"],
    resistances: ["Poison", "Bug"],
    immunes: ["Normal", "Fighting"],
  },
  {
    name: "Grass",
    weaknesses: ["Bug", "Fire", "Flying", "Ice", "Poison"],
    strengths: ["Ground", "Rock", "Water"],
    resistances: ["Water", "Electric", "Grass", "Ground"],
    immunes: [],
  },
  {
    name: "Ground",
    weaknesses: ["Grass", "Ice", "Water"],
    strengths: ["Electric", "Fire", "Poison", "Rock"],
    resistances: ["Poison", "Rock"],
    immunes: ["Electric"],
  },
  {
    name: "Ice",
    weaknesses: ["Fighting", "Fire", "Rock"],
    strengths: ["Flying", "Ground", "Grass", "Dragon"],
    resistances: ["Ice"],
    immunes: [],
  },
  {
    name: "Normal",
    weaknesses: ["Fighting"],
    strengths: [],
    resistances: [],
    immunes: ["Ghost"],
  },
  {
    name: "Poison",
    weaknesses: ["Ground", "Psychic"],
    strengths: ["Grass", "Bug"],
    resistances: ["Grass", "Fighting", "Poison"],
    immunes: [],
  },
  {
    name: "Psychic",
    weaknesses: ["Bug"],
    strengths: ["Fighting", "Poison"],
    resistances: ["Fighting", "Psychic"],
    immunes: [],
  },
  {
    name: "Rock",
    weaknesses: ["Fighting", "Grass", "Ground", "Water"],
    strengths: ["Bug", "Flying", "Fire", "Ice"],
    resistances: ["Normal", "Fire", "Flying", "Poison"],
    immunes: [],
  },
  {
    name: "Water",
    weaknesses: ["Electric", "Grass"],
    strengths: ["Fire", "Ground", "Rock"],
    resistances: ["Fire", "Water", "Ice"],
    immunes: [],
  },
];
